services:
  user-service:
    build: ./user-service
    image: user-service
    container_name: user-service
    ports:
      - "8007:8007"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/user
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - user-db

  university-service:
    build: ./university-service
    image: university-service
    container_name: university-service
    ports:
      - "8008:8008"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/university
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - university-db

  university-db:
    image: postgres:16-alpine
    container_name: university-db
    environment:
      - POSTGRES_DB=university
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    ports:
      - "6541:5432"

  user-db:
    image: postgres:16-alpine
    container_name: user-db
    environment:
      - POSTGRES_DB=user
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    ports:
      - "6540:5432"