DROP TABLE IF EXISTS agent_contacts CASCADE;
DROP TABLE IF EXISTS agent CASCADE;
DROP TABLE IF EXISTS student_socials CASCADE;
DROP TABLE IF EXISTS students CASCADE;
DROP TABLE IF EXISTS student_learns CASCADE;

CREATE TABLE IF NOT EXISTS student_learns (
    student_learn_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    university VARCHAR(255),
    course VARCHAR(100),
    course_name VARCHAR(255),
    program_id VARCHAR(100),
    rating FLOAT,
    exchange_programs_id INT
);

CREATE TABLE IF NOT EXISTS students (
    student_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    about_me VARCHAR(7000),
    resume_file BYTEA, --BYTEA BLOB
    first_name VARCHAR(100) NOT NULL,
    surname VARCHAR(100) NOT NULL,
    last_name VARCHAR(100),
    birth_date DATE,
    student_learn_id BIGINT REFERENCES student_learns(student_learn_id) ON DELETE CASCADE,
    avatar BYTEA --BYTEA BLOB
);

CREATE TABLE IF NOT EXISTS student_socials (
    socials_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(100),
    link VARCHAR(255),
    student_id BIGINT REFERENCES students(student_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS agent (
    agent_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    avatar BYTEA, --BYTEA BLOB
    email VARCHAR(255) UNIQUE NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    surname VARCHAR(100) NOT NULL,
    last_name VARCHAR(100),
    university_id INT
);

CREATE TABLE IF NOT EXISTS agent_contacts (
    agent_contacts_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(100),
    link VARCHAR(255),
    agent_id BIGINT REFERENCES agent(agent_id) ON DELETE CASCADE
);
