CREATE TABLE IF NOT EXISTS studentLearns (
    student_learn_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    university_id INT,
    course VARCHAR(100),
    program_id INT,
    rating FLOAT,
    exchange_programs_id INT
);

CREATE TABLE IF NOT EXISTS studentSocials (
    socials_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(100),
    link VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS students (
    student_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    about_me VARCHAR(7000),
    resume_file BYTEA,
    first_name VARCHAR(100) NOT NULL,
    surname VARCHAR(100) NOT NULL,
    last_name VARCHAR(100),
    birth_date DATE,
    learn_info_id INT REFERENCES studentLearns(student_learn_id) ON DELETE CASCADE,
    avatar BYTEA
    socials_id INT REFERENCES studentSocials(socials_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS agent (
    agent_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    avatar VARCHAR(255),
    email VARCHAR(255) UNIQUE NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    surname VARCHAR(100) NOT NULL,
    last_name VARCHAR(100),
    university_id INT
);

CREATE TABLE IF NOT EXISTS agentContacts (
    agentContacts_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(100),
    link VARCHAR(255),
    agent_id INT REFERENCES agent(agent_id) ON DELETE CASCADE
);