DROP TABLE IF EXISTS exchange_programs;
DROP TABLE IF EXISTS program_conditions;
DROP TABLE IF EXISTS uni_socials;
DROP TABLE IF EXISTS uni_geographic;
DROP TABLE IF EXISTS uni_info;

CREATE TABLE IF NOT EXISTS uni_info (
    uni_info_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(255),
    description VARCHAR(7000),
    avatar BIGINT,
    rating FLOAT
);

CREATE TABLE IF NOT EXISTS uni_geographic (
    uni_geographic_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    uni_info_id BIGINT REFERENCES uni_info(uni_info_id) ON DELETE CASCADE,
    filial_name VARCHAR(255),
    address VARCHAR(400)
);

CREATE TABLE IF NOT EXISTS uni_socials (
    uni_socials_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(100),
    link VARCHAR(255),
    uni_info_id BIGINT REFERENCES uni_info(uni_info_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS program_conditions (
    program_conditions_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    min_course INTEGER,
    min_rate FLOAT
);

CREATE TABLE IF NOT EXISTS agent (
    agent_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    avatar BIGINT, --BYTEA BLOB
    email VARCHAR(255) UNIQUE NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    surname VARCHAR(100) NOT NULL,
    last_name VARCHAR(100),
    university_id BIGINT
);

CREATE TABLE IF NOT EXISTS agent_contacts (
    agent_contacts_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(100),
    link VARCHAR(255),
    agent_id BIGINT REFERENCES agent(agent_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS exchange_programs (
    exchange_programs_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(255),
    description VARCHAR(7000),
    rating FLOAT,
    agent_email VARCHAR(200),
    program_conditions_id BIGINT REFERENCES program_conditions(program_conditions_id) ON DELETE CASCADE,
    uni_info_id BIGINT REFERENCES uni_info(uni_info_id) ON DELETE CASCADE
);